# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDKSampleApp' do
    inhibit_all_warnings!

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit', :tag => '5.0.3'
  pod 'SalesforceAnalytics',:path => '/Users/ajunaid001/Desktop/proj/mobile-sdk/SalesforceMobileSDK-iOS'
  pod 'SalesforceSDKCore',:path =>  '/Users/ajunaid001/Desktop/proj/mobile-sdk/SalesforceMobileSDK-iOS'
  pod 'SmartStore',:path =>  '/Users/ajunaid001/Desktop/proj/mobile-sdk/SalesforceMobileSDK-iOS'
  pod 'SmartSync',:path =>  '/Users/ajunaid001/Desktop/proj/mobile-sdk/SalesforceMobileSDK-iOS'
  pod 'SalesforceSwiftSDK',:path =>  '/Users/ajunaid001/Desktop/proj/mobile-sdk/SalesforceMobileSDK-iOS'

end
# Fix for xcode9/fmdb/sqlcipher/cocoapod issue - see https://discuss.zetetic.net/t/ios-11-xcode-issue-implicit-declaration-of-function-sqlite3-key-is-invalid-in-c99/2198/27
post_install do | installer |
    print "SQLCipher: link Pods/Headers/sqlite3.h"
    system "mkdir -p Pods/Headers/Private && ln -s ../../SQLCipher/sqlite3.h Pods/Headers/Private"
end
